export const routes = {
  HOME_SCREEN: 'HOME_SCREEN',
  TRADEMARK_SCREEN: 'TRADEMARK_SCREEN',
  FAVORITE_SCREEN: 'FAVORITE_SCREEN',
  NOTIFICATION_SCREEN: 'NOTIFICATION_SCREEN',
  USER_SCREEN: 'USER_SCREEN',
  CHATSCREEN: 'CHATSCREEN',
  BOTTOMTABBAR: 'BOTTOMTABBAR',
};
